<?
mysql_connect("localhost","xtwitter","xtwitter");
mysql_select_db("xtwitter");

$msg = $_REQUEST['message'];
if($msg != "")
	mysql_query("INSERT INTO messages (shout_at,content,user_id) VALUES(now(),'$msg',1);");

$tid = $_REQUEST['tid'];
if($tid != "")
	mysql_query("DELETE from messages where id=$tid;");

$result=mysql_query("SELECT * FROM messages order by shout_at desc");
$i=0;
?>

<html>
<head>
<title>杏坛推特</title>
<script language="javascript">
function del(id) {
	f_twitter.tid.value = id;
	f_twitter.submit();
}
</script>
</head>
<body>
<div id="header" style="float:left">
<div id="logo" style="float:left">
<img src="image/logo.png" width="200px" height="100px" />
</div>
<div id="ads" style="float:left">
广告位寻租
</div>
</div>
<div id="content">
<br/><br/><br/><br/><br/><br/><br/>
<div id="main_left">
<form id="f_twitter" action="main.php">
<textarea id="message" name="message"></textarea>
<input type="submit" value="推特">
<input type="hidden" id="tid" name="tid">
</p>
</form>
<ul>
<?
while( $row=mysql_fetch_array($result) ){
?>
<li><?= $row['shout_at'] ?><a href="javascript:del('<?= $row['id'] ?>');">删除</a><br/><?= $row['content'] ?></li>
<?
}
?>
</ul>
</div>
<div id="main_right" style="float:right">
。。。。。。
</div>
</div>
<div id="footer">
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.mrunix.net/webalizer/"><STRONG>Webalizer Version 2.01</STRONG></A>
</SMALL>
</TD>
<TD ALIGN="right" VALIGN="top">
<IMG SRC="image/msfree.png" ALT="100% Micro$oft free!">
</TD>
</TR>
</TABLE>
</div>
</body>
</html>