<?
error_reporting (E_ALL & ~E_NOTICE);

mysql_connect("localhost","xtwitter","xtwitter");
mysql_select_db("xtwitter");

$reply = $_REQUEST['reply'];
$pid = $_REQUEST['pid'];
if($reply != "")
	mysql_query("INSERT INTO messages (shout_at,content,user_id,parent_id) VALUES(now(),'$reply',1,$pid);");

$msg = $_REQUEST['message'];
if($msg != "")
	mysql_query("INSERT INTO messages (shout_at,content,user_id) VALUES(now(),'$msg',1);");

$tid = $_REQUEST['tid'];
if($tid != "")
	mysql_query("DELETE from messages where id=$tid;");

$result=mysql_query("SELECT * FROM messages where parent_id=0 order by shout_at desc");
$i=0;
?>

<html>
<head>
<title>杏坛推特</title>
<script src="javascript/jquery-1.5.2.min.js"></script>
<script src="javascript/custom.js"></script>
<script language="javascript">
$(function(){
	$('#btn1').click(loadXMLDoc);
	$('#btn2').click(loadXMLDoc2);
});

function del(id) {
	f_twitter.tid.value = id;
	f_twitter.submit();
}

function checkit() {
	msg = document.getElementById('message').value;
	if(msg == '')
		return false;
}

function showReply(tid) {
	tid = 'f_twitter_reply_' + tid;
	obj = document.getElementById(tid);
	obj.style.visibility = 'visible';
}

function hideReply(tid) {
	tid = 'f_twitter_reply_' + tid;
	obj = document.getElementById(tid);
	obj.style.visibility = 'hidden';
}

function loadXMLDoc()
{
$.ajax({
   url: "ajax_info.txt",
   success: function(msg){
     $('#myDiv')[0].innerHTML = msg;
   }
 });
}
function loadXMLDoc2()
{
$('#myDiv').fadeToggle('slow', function() {
    // Animation complete.
  });
}
</script>
</head>
<body>
<div id="header" style="float:left">
<div id="logo" style="float:left">
<img src="image/logo.png" width="200px" height="100px" />
</div>
<div id="ads" style="float:left">
广告位寻租
</div>
</div>
<div id="content">
<br/><br/><br/><br/><br/><br/><br/>
<button type="button" id='btn1'>Change Content</button>
<button type="button" id='btn2'>Change Content</button>
<div id="myDiv"></div><br/>
<div class="jquery_demo">
this is jquery demo!.
</div>
<br/><br/><br/><br/>
<div class="jquery_demo">
this is jquery demo2222!.
</div>

<div id="main_left">
<form method="post" id="f_twitter" action="main.php" onsubmit="javascript:return checkit();">
<textarea id="message" name="message"></textarea>
<input type="submit" value="推特">
<input type="hidden" id="tid" name="tid">
</p>
</form>
<ul>
<?
while( $row=mysql_fetch_array($result) ){
	$result_child=mysql_query("SELECT * FROM messages where parent_id=".$row['id']." order by shout_at desc");
?>
<li onmouseover="javascript:showReply(<?= $row['id'] ?>);" onmouseout="javascript:hideReply(<?= $row['id'] ?>);"><?= $row['shout_at'] ?><a href="javascript:del('<?= $row['id'] ?>');">删除</a><br/><?= $row['content'] ?>
<form id="f_twitter_reply_<?= $row['id'] ?>" action="main.php" style="visibility:hidden;">
<label>回复：</label>
<input type="text" value="" name="reply">
<input type="submit" value="回复">
<input type="hidden" id="pid" name="pid" value="<?= $row['id'] ?>">
</form>

<ul>
<?
	while( $row_child=mysql_fetch_array($result_child) ){
?>
<li><?= $row_child['shout_at'] ?><a href="javascript:del('<?= $row_child['id'] ?>');">删除</a><br/><?= $row_child['content'] ?></li>
<?
	}
?>
</ul>
</li>
<?
}
?>
</ul>
</div>
<div id="main_right" style="float:right">
。。。。。。
</div>
</div>
<div id="footer">
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.mrunix.net/webalizer/"><STRONG>Webalizer Version 2.01</STRONG></A>
</SMALL>
</TD>
<TD ALIGN="right" VALIGN="top">
<IMG SRC="image/msfree.png" ALT="100% Micro$oft free!">
</TD>
</TR>
</TABLE>
</div>
</body>
</html>